version: '3'

services:
  php-8.1-libxml-2.9.13: &template
    build:
      context: ./docker/php
      args:
        LIBXML_VERSION: 2.9.13
        PHP_VERSION: 8.1
    volumes:
      - ./:/app
    tty: true

  php-8.1-libxml-2.9.14:
    <<: *template
    build:
      context: ./docker/php
      args:
        LIBXML_VERSION: 2.9.14
        PHP_VERSION: 8.1

  php-8.2-libxml-2.9.13:
    <<: *template
    build:
      context: ./docker/php
      args:
        LIBXML_VERSION: 2.9.13
        PHP_VERSION: 8.2

  php-8.2-libxml-2.9.14:
    <<: *template
    build:
      context: ./docker/php
      args:
        LIBXML_VERSION: 2.9.14
        PHP_VERSION: 8.2

  php-8.3-libxml-2.9.13:
    <<: *template
    build:
      context: ./docker/php
      args:
        LIBXML_VERSION: 2.9.13
        PHP_VERSION: 8.3

  php-8.3-libxml-2.9.14:
    <<: *template
    build:
      context: ./docker/php
      args:
        LIBXML_VERSION: 2.9.14
        PHP_VERSION: 8.3